// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeViewer: typeof import('./src/components/CodeViewer.vue')['default']
    Face: typeof import('./src/components/face.vue')['default']
    Model_info_manage_addserver: typeof import('./src/components/model_info_manage_addserver.vue')['default']
    Model_info_manage_deploy: typeof import('./src/components/model_info_manage_deploy.vue')['default']
    Model_info_manage_overview: typeof import('./src/components/model_info_manage_overview.vue')['default']
    Model_info_manage_test: typeof import('./src/components/model_info_manage_test.vue')['default']
    Model_manage_item: typeof import('./src/components/model_manage_item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User_info: typeof import('./src/components/user_info.vue')['default']
  }
}
